[project]
name = "linear-regression-house-price"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "muhammad.faraz", email = "muhammadfarazeng@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
linear-regression-house-price = "linear_regression_house_price:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
